---
abstract: 'Interface to Mortgage Payment Calculator.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Moose: 2.0006
  Moose::Util::TypeConstraints: 2.0006
  namespace::clean: 0.20
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Calculator-MortgagePayment
provides:
  Calculator::MortgagePayment:
    file: lib/Calculator/MortgagePayment.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
